services:
  - type: web
    name: chat-app
    env: python
    runtime: python-3.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chat-app-db
          property: connectionString

databases:
  - name: chat-app-db
    databaseName: chatapp
    user: chatapp

